version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    working_directory: ~/react-application
  steps:
    - checkout
    - attach_workspace:
        at: ~/react-application
    - run: yarn install
    - run: yarn build
    - persist_to_workspace:
        root: .
        paths: dist
  deploy:
    docker:
      - image: circleci/golang:1.9.6
    parallelism: 1
    working_directory: ~/react-application
    steps:
    - checkout
    - attach_workspace:
        at: ~/react-application
    - restore_cache:
        key: v1-pkg-cache
    - run: go get -v github.com/bep/s3deploy
    - save_cache:
        key: v1-pkg-cache
        paths:
           - /go/pkg
    - run:
      name: Deploy to S3
      command: |
        s3deploy -source=dist/ -region=us-east-1 -key=AKIA44LYRJDSHKF24Z55 -secret=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 -distribution-id=ETF5Q5SIH28CK -bucket=vinayreactapp
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
      - deploy:
        requires:
          - build
            filters:
              branches:
                only:
                  - master